matrix:
  NAME:
    - ukhomeofficedigital/dsa-confluence
  DOCKER_REPO:
    - quay.io
  DOCKER_USERNAME:
    - ukhomeofficedigital+dsa_shared_services_metrics

pipeline:
  docker-build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dsa-shared-services-metrics
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    dockerfile: dockerfile
    force_tag: true
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
      - build-${DRONE_BUILD_NUMBER}
    when:
      event: push 

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - ENV=dsa-shs-dev
      - KUBE_NAMESPACE=dsa-shs-dev
      - INSECURE_SKIP_TLS_VERIFY=true
      - VOLUME_SIZE=10Gi
    secrets:
      - kube_token_dsa_shs_dev
      - dev_kube_server
    commands:
      - export KUBE_TOKEN=$$kube_token_dsa_shs_dev
      - export KUBE_SERVER=$$dev_kube_server
      - kd -f kube/service.yml -f kube/network-policy.yml \
        kube/deployment.yml
    when:
      branch: development
      event: push

  #deploy_to_prod:
  #  image: quay.io/ukhomeofficedigital/kd
  #  environment:
  #    - ENV=prod
  #    - KUBE_NAMESPACE=dsa-shs-prod
  #    - INSECURE_SKIP_TLS_VERIFY=true
  #    - VOLUME_SIZE=10Gi
  #  secrets:
  #    - kube_token_dsa_shs_prod
  #  commands:
  #    - export kube_token_dsa_shs_prod=$$PROD_KUBE_TOKEN
  #    - kd --delete --file deployment.yml
  #    - kd -f deployment.yml -f deployment.yml
  #  when:
  #    environment: production
  #    branch: master
  #    event: deployment
